const fs = require("fs")
const writeStream = fs.createWriteStream("./text2.log")
writeStream.write("sdfsdfsdfsdfsdfsdfsd")
writeStream.write("sdfsdfsdfsdfsdfsdfsd")
writeStream.write("sdfsdfsdfsdfsdfsdfsd")
writeStream.write("sdfsdfsdfsdfsdfsdfsd\n")
writeStream.write("sdfsdfsdfsdfsdfsdfsd")
writeStream.write("sdfsdfsdfsdfsdfsdfsd")
writeStream.write("sdfsdfsdfsdfsdfsdfsd")
writeStream.write("sdfsdfsdfsdfsdfsdfsd")
writeStream.write("sdfsdfsdfsdfsdfsdfsd")
writeStream.write("sdfsdfsdfsdfsdfsdfsd")
writeStream.close()